### ISSUE TITLE
GraphQL ruby 

### ISSUE THREAD

**Issue by eshaiju** [edymerchk/awesome-ruby-api#15]
Can we add GraphQL ruby https://github.com/rmosolgo/graphql-ruby here?
Which category can we add graphql?

**Comment by eshaiju** [comment]
@edymerchk

**Comment by edymerchk** [comment]
@eshaiju yes, I think makes sense to add it under `Frameworks`

**Comment by eshaiju** [comment]
https://github.com/edymerchk/awesome-ruby-api/pull/17 
Please check this. I think we can even think of having a separate session for GraphQL tools. or else I can add tools in different sessions.
