### ISSUE TITLE
add more articles

### ISSUE THREAD

**Issue by edymerchk** [edymerchk/awesome-ruby-api#3]

**Comment by pulkit-singhal** [comment]
Can i work on this ?

**Comment by edymerchk** [comment]
@pulkit-singhal sure! just follow the format:

`[LIBRARY](LINK) - DESCRIPTION.`

and make the PR 😄

**Comment by sebasjimenez10** [comment]
https://github.com/edymerchk/awesome-ruby-api/pull/9 😄
